name: "DMRHost SD-Images"
on:
  pull_request:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: "image builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/cachix-action@v6
      with:
        name: nixinstall-kexec
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # skipPush: true
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |      
       nix-build nix/default.nix -A builder -o builder
       cd nix/image
       ../../builder/bin/builder --argstr system armv6l-linux
       ../../builder/bin/builder --argstr system armv7l-linux       
       ../../builder/bin/builder --argstr system aarch64-linux
