name: "DMRHost SD-Images"
on:
  pull_request:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: "Image Builder"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [armv6l-linux, armv7l-linux, aarch64-linux]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/cachix-action@v8
      with:
        name: dmrhost-image
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY_DMRHOST_IMAGE }}'
        # skipPush: true
    - run: |      
       nix-build nix/default.nix -A builder -o build
       cd nix/image
       ../../build/bin/build --argstr system ${{ matrix.target }}
